-- MATERIAL --

INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (NEXT_PK_MATERIAL_ID.NEXTVAL,'LADRILLO','UNIDAD',1000.0,5000);
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (NEXT_PK_MATERIAL_ID.NEXTVAL,'VARILLA','UNIDAD',15000.0,1000);
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (NEXT_PK_MATERIAL_ID.NEXTVAL,'ARENA','METRO',25000.0,70);
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (NEXT_PK_MATERIAL_ID.NEXTVAL,NULL,NULL,NULL,NULL);
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (NEXT_PK_MATERIAL_ID.NEXTVAL,NULL,NULL,NULL,NULL);
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (NEXT_PK_MATERIAL_ID.NEXTVAL,NULL,NULL,NULL,NULL);
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (NEXT_PK_MATERIAL_ID.NEXTVAL,NULL,NULL,NULL,NULL);
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (NEXT_PK_MATERIAL_ID.NEXTVAL,NULL,NULL,NULL,NULL);

-- PROVEEDOR --

INSERT INTO PROVEEDOR (PROVEEDOR_ID, NIT_PROV, NOMBRE, TEL, CEL, URL, EMAIL) VALUES (NEXT_PK_PROVEEDOR_ID.NEXTVAL,'800-91211','ARGOS',NULL,NULL,NULL,NULL);
INSERT INTO PROVEEDOR (PROVEEDOR_ID, NIT_PROV, NOMBRE, TEL, CEL, URL, EMAIL) VALUES (NEXT_PK_PROVEEDOR_ID.NEXTVAL,'801-10561','CONCRETODO',NULL,NULL,NULL,NULL);
INSERT INTO PROVEEDOR (PROVEEDOR_ID, NIT_PROV, NOMBRE, TEL, CEL, URL, EMAIL) VALUES (NEXT_PK_PROVEEDOR_ID.NEXTVAL,'900-12356','PISENDE',NULL,NULL,NULL,NULL);
INSERT INTO PROVEEDOR (PROVEEDOR_ID, NIT_PROV, NOMBRE, TEL, CEL, URL, EMAIL) VALUES (NEXT_PK_PROVEEDOR_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO PROVEEDOR (PROVEEDOR_ID, NIT_PROV, NOMBRE, TEL, CEL, URL, EMAIL) VALUES (NEXT_PK_PROVEEDOR_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL);

-- MAESTRO --

INSERT INTO MAESTRO (MAESTRO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL) VALUES (NEXT_PK_MAESTRO_ID.NEXTVAL,NULL,'PEDRO','ARANGO',NULL,NULL,NULL);
INSERT INTO MAESTRO (MAESTRO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL) VALUES (NEXT_PK_MAESTRO_ID.NEXTVAL,NULL,'JUAN','HENAO',NULL,NULL,NULL);
INSERT INTO MAESTRO (MAESTRO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL) VALUES (NEXT_PK_MAESTRO_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO MAESTRO (MAESTRO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL) VALUES (NEXT_PK_MAESTRO_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO MAESTRO (MAESTRO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL) VALUES (NEXT_PK_MAESTRO_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL);

-- INGENIERO --

INSERT INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (NEXT_PK_INGENIERO_ID.NEXTVAL,NULL,'JUAN','PABLO','HENAO','ARANGO',NULL,NULL);
INSERT INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (NEXT_PK_INGENIERO_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (NEXT_PK_INGENIERO_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (NEXT_PK_INGENIERO_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (NEXT_PK_INGENIERO_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (NEXT_PK_INGENIERO_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (NEXT_PK_INGENIERO_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (NEXT_PK_INGENIERO_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (NEXT_PK_INGENIERO_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- TIPO_OBRA --

INSERT INTO TIPO_OBRA (TIPO_OBRA_ID, TIPO_OBRA) VALUES (NEXT_PK_TIPO_OBRA_ID.NEXTVAL,'EDIFICIO');
INSERT INTO TIPO_OBRA (TIPO_OBRA_ID, TIPO_OBRA) VALUES (NEXT_PK_TIPO_OBRA_ID.NEXTVAL,'CASA');
INSERT INTO TIPO_OBRA (TIPO_OBRA_ID, TIPO_OBRA) VALUES (NEXT_PK_TIPO_OBRA_ID.NEXTVAL,'CENTRO COMERCIAL');
INSERT INTO TIPO_OBRA (TIPO_OBRA_ID, TIPO_OBRA) VALUES (NEXT_PK_TIPO_OBRA_ID.NEXTVAL,'URBANIZACION');
INSERT INTO TIPO_OBRA (TIPO_OBRA_ID, TIPO_OBRA) VALUES (NEXT_PK_TIPO_OBRA_ID.NEXTVAL,'BODEGA');
INSERT INTO TIPO_OBRA (TIPO_OBRA_ID, TIPO_OBRA) VALUES (NEXT_PK_TIPO_OBRA_ID.NEXTVAL,'PARELACIÓN');

-- CLIENTE --

INSERT INTO CLIENTE (CLIENTE_ID, DOC_IDENTIDAD, TIPO_DOC, NOM1, NOM2, APE1, APE2) VALUES (NEXT_PK_CLIENTE_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO CLIENTE (CLIENTE_ID, DOC_IDENTIDAD, TIPO_DOC, NOM1, NOM2, APE1, APE2) VALUES (NEXT_PK_CLIENTE_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO CLIENTE (CLIENTE_ID, DOC_IDENTIDAD, TIPO_DOC, NOM1, NOM2, APE1, APE2) VALUES (NEXT_PK_CLIENTE_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO CLIENTE (CLIENTE_ID, DOC_IDENTIDAD, TIPO_DOC, NOM1, NOM2, APE1, APE2) VALUES (NEXT_PK_CLIENTE_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO CLIENTE (CLIENTE_ID, DOC_IDENTIDAD, TIPO_DOC, NOM1, NOM2, APE1, APE2) VALUES (NEXT_PK_CLIENTE_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO CLIENTE (CLIENTE_ID, DOC_IDENTIDAD, TIPO_DOC, NOM1, NOM2, APE1, APE2) VALUES (NEXT_PK_CLIENTE_ID.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL);

-- COMPRA --

INSERT INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (NEXT_PK_NRO_FACTURA.NEXTVAL,'2/02/05',2775000,90);
INSERT INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (NEXT_PK_NRO_FACTURA.NEXTVAL,NULL,1136000,91);
INSERT INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (NEXT_PK_NRO_FACTURA.NEXTVAL,NULL,5540000,92);
INSERT INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (NEXT_PK_NRO_FACTURA.NEXTVAL,NULL,650000,93);

-- COMPRA_MATERIAL --

INSERT INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (NEXT_PK_COMPRA_MATERIAL_ID.NEXTVAL,500,10,100,20000,2000000);
INSERT INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (NEXT_PK_COMPRA_MATERIAL_ID.NEXTVAL,500,11,150,500,75000);
INSERT INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (NEXT_PK_COMPRA_MATERIAL_ID.NEXTVAL,500,12,50,14000,700000);
INSERT INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (NEXT_PK_COMPRA_MATERIAL_ID.NEXTVAL,501,10,20,19000,380000);
INSERT INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (NEXT_PK_COMPRA_MATERIAL_ID.NEXTVAL,502,11,10,600,6000);
INSERT INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (NEXT_PK_COMPRA_MATERIAL_ID.NEXTVAL,502,13,50,15000,750000);
INSERT INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (NEXT_PK_COMPRA_MATERIAL_ID.NEXTVAL,503,14,200,25000,5000000);
INSERT INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (NEXT_PK_COMPRA_MATERIAL_ID.NEXTVAL,503,11,30,18000,540000);
INSERT INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (NEXT_PK_COMPRA_MATERIAL_ID.NEXTVAL,503,13,50,13000,650000);

-- OBRA --

INSERT INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (NEXT_PK_OBRA.NEXTVAL,'2/03/05',NULL,NULL,NULL,NULL,NULL,20,70,51);
INSERT INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (NEXT_PK_OBRA.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,21,71,52);
INSERT INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (NEXT_PK_OBRA.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,23,71,50);
INSERT INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (NEXT_PK_OBRA.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,24,73,53);
INSERT INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (NEXT_PK_OBRA.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,21,74,54);
INSERT INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (NEXT_PK_OBRA.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,21,71,55);
INSERT INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (NEXT_PK_OBRA.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,21,72,51);
INSERT INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (NEXT_PK_OBRA.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,22,71,52);
INSERT INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (NEXT_PK_OBRA.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,22,72,50);
INSERT INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (NEXT_PK_OBRA.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,23,73,53);
INSERT INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (NEXT_PK_OBRA.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,24,74,54);
INSERT INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (NEXT_PK_OBRA.NEXTVAL,NULL,NULL,NULL,NULL,NULL,NULL,25,72,55);

-- OBRA_MAESTRO --

INSERT INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (NEXT_PK_OBRA_MAESTRO.NEXTVAL,1,30,'27/07/23');
INSERT INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (NEXT_PK_OBRA_MAESTRO.NEXTVAL,1,32,'29/01/23');
INSERT INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (NEXT_PK_OBRA_MAESTRO.NEXTVAL,1,33,'12/01/23');
INSERT INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (NEXT_PK_OBRA_MAESTRO.NEXTVAL,1,34,'10/04/23');
INSERT INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (NEXT_PK_OBRA_MAESTRO.NEXTVAL,2,30,'9/05/23');
INSERT INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (NEXT_PK_OBRA_MAESTRO.NEXTVAL,2,31,'19/12/23');
INSERT INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (NEXT_PK_OBRA_MAESTRO.NEXTVAL,2,32,'19/02/23');
INSERT INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (NEXT_PK_OBRA_MAESTRO.NEXTVAL,2,33,'3/12/23');

-- DETALLE_OBRA --

INSERT INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (NEXT_PK_DETALLE_OBRA.NEXTVAL,1,11,50,20000,1000000);
INSERT INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (NEXT_PK_DETALLE_OBRA.NEXTVAL,1,12,2000,1000,2000000); 
INSERT INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (NEXT_PK_DETALLE_OBRA.NEXTVAL,1,13,50,15000,750000);
INSERT INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (NEXT_PK_DETALLE_OBRA.NEXTVAL,1,14,20,25000,500000);
INSERT INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (NEXT_PK_DETALLE_OBRA.NEXTVAL,2,11,50,20000,1000000);
INSERT INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (NEXT_PK_DETALLE_OBRA.NEXTVAL,2,12,2000,1000,2000000);
INSERT INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (NEXT_PK_DETALLE_OBRA.NEXTVAL,2,13,20,15000,300000);
INSERT INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (NEXT_PK_DETALLE_OBRA.NEXTVAL,2,14,70,25000,1750000);
INSERT INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (NEXT_PK_DETALLE_OBRA.NEXTVAL,2,13,20,15000,300000);
INSERT INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (NEXT_PK_DETALLE_OBRA.NEXTVAL,2,14,70,25000,1750000);


-- DELETE ENTRIES --
DELETE FROM OBRA_MAESTRO;

DELETE FROM DETALLE_OBRA;

DELETE FROM OBRA;

DELETE FROM COMPRA_MATERIAL;

DELETE FROM COMPRA;

DELETE FROM CLIENTE;

DELETE FROM TIPO_OBRA;

DELETE FROM INGENIERO;

DELETE FROM MAESTRO;

DELETE FROM PROVEEDOR;

DELETE FROM MATERIAL;


-- INSERTIONS WITH HARCODED IDS --

-- MATERIAL --

INSERT ALL 
INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (10, 'CEMENTO', 'BULTO', 20000, 100)
INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (11, 'LADRILLO', 'UNIDAD', 1000, 5000)
INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (12, 'VARILLA', 'UNIDAD', 15000, 1000)
INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (13, 'ARENA', 'METRO', 25000, 0)
INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (14, 'MADERA', 'UNIDAD', 10000, 200)
INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (15, 'PINTURA', 'UNIDAD', 30000, 50)
INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (16, 'TORNILLO', 'METRO', 500, 10000)
INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (17, 'ALAMBRE', 'METRO', 8000, 0)
INTO MATERIAL (MATERIAL_ID, MATERIAL, UNIDAD_MED, COSTO, EXISTENCIA) VALUES (18, 'HIERRO', 'UNIDAD', 12000, 150)
SELECT 1 FROM DUAL;

-- PROVEEDOR --

INSERT ALL 
INTO PROVEEDOR (PROVEEDOR_ID, NIT_PROV, NOMBRE, TEL, URL, EMAIL, CEL) VALUES (90, '800-91211', 'ARGOS', NULL, NULL, NULL, NULL)
INTO PROVEEDOR (PROVEEDOR_ID, NIT_PROV, NOMBRE, TEL, URL, EMAIL, CEL) VALUES (91, '801-10561', 'CONCRETODO', NULL, NULL, NULL, NULL)
INTO PROVEEDOR (PROVEEDOR_ID, NIT_PROV, NOMBRE, TEL, URL, EMAIL, CEL) VALUES (92, '900-12356', 'PISENDE', NULL, NULL, NULL, NULL)
INTO PROVEEDOR (PROVEEDOR_ID, NIT_PROV, NOMBRE, TEL, URL, EMAIL, CEL) VALUES (93, NULL, 'HOMECENTER', NULL, NULL, NULL, NULL)
INTO PROVEEDOR (PROVEEDOR_ID, NIT_PROV, NOMBRE, TEL, URL, EMAIL, CEL) VALUES (94, NULL, 'DISTRIHOGAR', NULL, NULL, NULL, NULL)
SELECT 1 FROM DUAL;

-- MAESTRO --

INSERT ALL 
INTO MAESTRO (MAESTRO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL) VALUES (30, '123456789', 'PEDRO', 'ARANGO', 'GONZALEZ', 'SUAREZ', '3219876543')
INTO MAESTRO (MAESTRO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL) VALUES (31, '987654321', 'JUAN', 'HENAO', 'CASTRO', 'LOPEZ', '3201234567')
INTO MAESTRO (MAESTRO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL) VALUES (32, '9871392849', 'SANTIAGO', NULL, 'MOSQUERA', 'RUIZ', '3208917876')
INTO MAESTRO (MAESTRO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL) VALUES (33, '7058981', 'FRANCISCO', 'ANDRES', 'MARIN', 'BENAVIDES', '3205917833')
INTO MAESTRO (MAESTRO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL) VALUES (34, '10384829812', 'JOSE', NULL, 'MERIDA', 'ARABIA', '3205475849')
SELECT 1 FROM DUAL

-- INGENIERO --

INSERT ALL 
INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (20, 1001, 'JUAN', 'PABLO', 'HENAO', 'ARANGO', 123456789, 'JUAN.PABLO@EMAIL.COM')
INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (21, 1002, 'LUIS', NULL, 'TORO', NULL, 987654321, 'LUIS.TORO@EMAIL.COM')
INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (22, 1003, 'MARIA', 'FERNANDA', NULL, 'LOPEZ', 555555555, 'MARIA.LOPEZ@EMAIL.COM')
INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (23, 1004, 'PEDRO', NULL, 'ENRIQUE', 'RIVERA', 111111111, 'PEDRO.RIVERA@EMAIL.COM')
INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (24, 1005, 'ANA', 'CAROLINA', 'GOMEZ', 'TORO', 999999999, 'ANA.GOMEZ@EMAIL.COM')
INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (25, 1006, 'CARLOS', NULL, 'MENDEZ', NULL, 777777777, 'CARLOS.MENDEZ@EMAIL.COM')
INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (26, 1007, 'LAURA', 'VICTORIA', 'MARTINEZ', NULL, 333333333, 'LAURA.MARTINEZ@EMAIL.COM')
INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (27, 1008, 'ANDRES', 'FELIPE', 'PEREZ', 'GARCIA', 444444444, 'ANDRES.PEREZ@EMAIL.COM')
INTO INGENIERO (INGENIERO_ID, DOC_IDENT, NOM1, NOM2, APE1, APE2, CEL, EMAIL) VALUES (28, 1009, 'PATRICIA', NULL, NULL, NULL, 666666666, 'PATRICIA@EMAIL.COM')
SELECT 1 FROM DUAL;

-- TIPO_OBRA --

INSERT ALL 
INTO TIPO_OBRA (TIPO_OBRA_ID, TIPO_OBRA) VALUES (70,'EDIFICIO')
INTO TIPO_OBRA (TIPO_OBRA_ID, TIPO_OBRA) VALUES (71,'CASA')
INTO TIPO_OBRA (TIPO_OBRA_ID, TIPO_OBRA) VALUES (72,'CENTRO COMERCIAL')
INTO TIPO_OBRA (TIPO_OBRA_ID, TIPO_OBRA) VALUES (73,'URBANIZACION')
INTO TIPO_OBRA (TIPO_OBRA_ID, TIPO_OBRA) VALUES (74,'BODEGA')
INTO TIPO_OBRA (TIPO_OBRA_ID, TIPO_OBRA) VALUES (75,'PARELACIÓN')
SELECT 1 FROM DUAL;

-- CLIENTE --

INSERT ALL
INTO CLIENTE (CLIENTE_ID, DOC_IDENTIDAD, TIPO_DOC, NOM1, NOM2, APE1, APE2) VALUES (50, 234567890, 'CEDULA_CIUDADANIA',               'JOHN',     'ROBERT',   'DOE',          'SMITH'),
INTO CLIENTE (CLIENTE_ID, DOC_IDENTIDAD, TIPO_DOC, NOM1, NOM2, APE1, APE2) VALUES (51, 9876543210, 'CEDULA_EXTRANJERIA',   'MARIA',    'ISABELLA', 'GOMEZ',        'RODRIGUEZ')
INTO CLIENTE (CLIENTE_ID, DOC_IDENTIDAD, TIPO_DOC, NOM1, NOM2, APE1, APE2) VALUES (52, NULL,       'TARJETA_IDENTIDAD',    'CARLOS',   NULL,       'PEREZ',        'GUTIERREZ')
INTO CLIENTE (CLIENTE_ID, DOC_IDENTIDAD, TIPO_DOC, NOM1, NOM2, APE1, APE2) VALUES (53, 1122334455, 'NIT',                  'LAURA',    'VIVIAN',   'MARTINEZ',     'LOPEZ')
INTO CLIENTE (CLIENTE_ID, DOC_IDENTIDAD, TIPO_DOC, NOM1, NOM2, APE1, APE2) VALUES (54, 9988776655, 'RUT',                  'PEDRO',    'ANDRES',   'SANCHEZ',      'RAMIREZ')
INTO CLIENTE (CLIENTE_ID, DOC_IDENTIDAD, TIPO_DOC, NOM1, NOM2, APE1, APE2) VALUES (55, 5544332211, 'CEDULA_CIUDADANIA',    'ANA',      'CECILIA',  'GUTIERREZ',    'LOPEZ')
SELECT 1 FROM DUAL;

-- COMPRA --

INSERT ALL
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (500, '02/02/05', 2775000, 90)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (501, '04/11/22', 380000, 91)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (502, '10/03/14', 756000, 92)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (503, '05/08/06', 6190000, 93)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (504, '21/07/09', 2467120, 90)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (505, '27/07/13', 806883, 91)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (506, '16/01/22', 8536572, 93)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (507, '11/01/08', 1150317, 92)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (508, '09/07/04', 8891883, 90)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (509, '21/07/06', 6170544, 90)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (510, '22/11/13', 315144, 94)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (511, '30/10/10', 12486705, 90)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (512, '19/01/01', 914793, 94)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (513, '15/11/01', 4520043, 93)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (514, '19/12/23', 1453525, 90)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (515, '02/04/11', 29158444, 90)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (516, '28/04/14', 4335705, 91)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (517, '19/12/11', 15111795, 90)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (518, '20/12/17', 5386877, 91)
INTO COMPRA (NRO_FACTURA, FECHA, TOTAL_PAGAR, PROVEEDOR_ID) VALUES (519, '12/11/15', 4335705, 91)
SELECT 1 FROM DUAL;

-- COMPRA_MATERIAL --

INSERT ALL
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (1, 500, 10, 100, 20000, 2000000)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (2, 500, 11, 150, 500, 75000)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (3, 500, 12, 50, 14000, 700000)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (4, 501, 10, 20, 19000, 380000)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (5, 502, 11, 10, 600, 6000)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (6, 502, 13, 50, 15000, 750000)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (7, 503, 14, 200, 25000, 5000000)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (8, 503, 11, 30, 18000, 540000)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (9, 503, 13, 50, 13000, 650000)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (10, 504, 18, 100, 15000, 1500000)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (11, 504, 14, 77, 12560, 967120)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (12, 508, 10, 819, 10857, 8891883)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (13, 506, 14, 354, 3546, 1255284)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (14, 505, 18, 499, 1617, 806883)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (15, 506, 17, 504, 14447, 7281288)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (16, 507, 12, 171, 6727, 1150317)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (17, 514, 11, 265, 5485, 1453525)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (18, 509, 10, 657, 9392, 6170544)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (19, 518, 14, 61, 18962, 1156682)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (20, 515, 15, 599, 7901, 4732699)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (21, 510, 13, 216, 1459, 315144)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (22, 517, 10, 809, 15963, 12914067)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (23, 515, 10, 305, 17928, 5468040)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (24, 515, 10, 955, 19851, 18957705)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (25, 511, 14, 627, 13000, 8151000)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (26, 511, 14, 627, 6915, 4335705)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (27, 512, 14, 627, 1459, 914793)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (28, 513, 14, 627, 7209, 4520043)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (29, 516, 14, 627, 6915, 4335705)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (30, 519, 11, 627, 6915, 4335705)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (31, 517, 12, 234, 9392, 2197728)
INTO COMPRA_MATERIAL (COMPRA_MATERIAL_ID, NRO_FACTURA, MATERIAL_ID, CANTIDAD, COSTO_UNID, TOTAL) VALUES (32, 518, 18, 265, 15963, 4230195)
SELECT 1 FROM DUAL;

-- OBRA --

INSERT ALL 
INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (1, '2/03/05', 'CONTADO', NULL, NULL, NULL, NULL, 20, 70, 51)
INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (2, '30/11/23', '1 AÑO', NULL, NULL, NULL, NULL, 21, 71, 52)
INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (3, '28/11/01', 'CONTADO', NULL, NULL, NULL, NULL, 23, 71, 50)
INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (4, '14/06/03', '1 AÑO', NULL, NULL, NULL, NULL, 24, 73, 53)
INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (5, '19/09/22', '6 MESES', NULL, NULL, NULL, NULL, 21, 74, 54)
INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (6, '02/07/09', '1 AÑO', NULL, NULL, NULL, NULL, 21, 71, 55)
INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (7, '21/04/22', 'CONTADO', NULL, NULL, NULL, NULL, 21, 72, 51)
INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (8, '10/10/18', '6 MESES', NULL, NULL, NULL, NULL, 22, 71, 52)
INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (9, '30/03/22', '1 AÑO', NULL, NULL, NULL, NULL, 22, 72, 50)
INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (10, '23/12/07', 'CONTADO', NULL, NULL, NULL, NULL, 23, 73, 53)
INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (11, '08/01/19', '6 MESES', NULL, NULL, NULL, NULL, 24, 74, 54)
INTO OBRA (NRO_OBRA, FECHA, FORMA_PAGO, VALOR_TOTAL, PLAZO, PAGO_INICIAL, SALDO, INGENIERO_ID, TIPO_OBRA_ID, CLIENTE_ID) VALUES (12, '15/02/23', '1 AÑO', NULL, NULL, NULL, NULL, 25, 72, 55)
SELECT 1 FROM DUAL;

-- OBRA_MAESTRO --

INSERT ALL
INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (1, 1, 30, '27/07/23')
INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (2, 1, 32, '29/01/23')
INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (3, 1, 33, '12/01/23')
INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (4, 1, 34, '10/04/23')
INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (5, 2, 30, '9/05/23')
INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (6, 2, 31, '19/12/23')
INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (7, 2, 32, '19/02/23')
INTO OBRA_MAESTRO (DETALLE_OBRA_MAESTRO_ID, NRO_OBRA, MAESTRO_ID, FECHA_INGRESO) VALUES (8, 2, 33, '3/12/23')
SELECT 1 FROM DUAL;

-- DETALLE_OBRA --

INSERT ALL
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (1, 1, 11, 50, 20.000, 1000000)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (2, 1, 12, 2000, 1.000, 2000000)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (3, 1, 13, 50, 15.000, 750000)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (4, 1, 14, 20, 25.000, 500000)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (5, 2, 11, 50, 20.000, 1000000)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (6, 2, 12, 2000, 1.000, 2000000)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (7, 2, 13, 20, 15.000, 300000)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (8, 2, 14, 70, 25.000, 1750000)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (9, 2, 13, 20, 15.000, 300000)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (10, 3, 14, 70, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (11, 3, 10, 100, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (12, 4, 15, 200, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (13, 4, 16, 300, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (14, 4, 17, 150, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (15, 5, 11, 30, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (16, 6, 13, 40, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (17, 6, 14, 60, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (18, 7, 12, 1000, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (19, 8, 16, 500, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (20, 9, 11, 80, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (21, 9, 14, 120, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (22, 10, 13, 10, NULL, NULL)
INTO DETALLE_OBRA (DETALLE_OBRA_ID, NRO_OBRA, MATERIAL_ID, CANTIDAD, COSTO, TOTAL) VALUES (23, 11, 14, 50, NULL, NULL)
SELECT 1 FROM DUAL;