
SELECT *
FROM MATERIAL
ORDER BY MATERIAL.MATERIAL_ID

SELECT O.NRO_OBRA, O.FECHA, O.FORMA_PAGO, O.VALOR_TOTAL,
(ING.NOM1||' '||ING.NOM2||' '||ING.APE1||' '||ING.APE2) AS ING_CARGO,
(M.NOM1||' '||M.NOM2||' '||M.APE1||' '||M.APE2) AS MAESTRO_OBRA,
Ma.MATERIAL
FROM OBRA O
INNER JOIN INGENIERO ING   ON ING.INGENIERO_ID = O.INGENIERO_ID
INNER JOIN OBRA_MAESTRO OM ON OM.NRO_OBRA = O.NRO_OBRA
INNER JOIN MAESTRO M       ON M.MAESTRO_ID = OM.MAESTRO_ID
INNER JOIN DETALLE_OBRA DO ON DO.NRO_OBRA = O.NRO_OBRA
INNER JOIN MATERIAL Ma     ON Ma.MATERIAL_ID = DO.MATERIAL_ID;

SELECT *
FROM MATERIAL
WHERE COSTO >= 15000 AND COSTO <= 20000 AND EXISTENCIA >= 100;

SELECT O.NRO_OBRA, O.FECHA, O.VALOR_TOTAL, M.MAESTRO_ID, M.DOC_IDENT,
(M.NOM1||' '||M.NOM2||' '||M.APE1||' '||M.APE2) AS MAESTRO_OBRA,
(ING.NOM1||' '||ING.NOM2||' '||ING.APE1||' '||ING.APE2) AS ING_CARGO,
Ma.MATERIAL_ID, Ma.EXISTENCIA, Ma.MATERIAL,
T_O.TIPO_OBRA_ID, T_O.TIPO_OBRA
FROM OBRA O
INNER JOIN INGENIERO ING   ON ING.INGENIERO_ID = O.INGENIERO_ID
INNER JOIN OBRA_MAESTRO OM ON OM.NRO_OBRA = O.NRO_OBRA
INNER JOIN MAESTRO M       ON M.MAESTRO_ID = OM.MAESTRO_ID
INNER JOIN DETALLE_OBRA DO ON DO.NRO_OBRA = O.NRO_OBRA
INNER JOIN MATERIAL Ma     ON Ma.MATERIAL_ID = DO.MATERIAL_ID
INNER JOIN TIPO_OBRA T_O    ON TO.TIPO_OBRA_ID = O.TIPO_OBRA_ID
WHERE ING.NOM1 = 'JUAN' 
AND ING.NOM2 = 'PABLO' 
AND ING.APE1 = 'HENAO'
AND ING.APE2 = 'ARANGO';

SELECT DISTINCT O.NRO_OBRA, O.FECHA, O.VALOR_TOTAL, M.MAESTRO_ID, M.DOC_IDENT, 
(M.NOM1||' '||M.NOM2||' '||M.APE1||' '||M.APE2) AS MAESTRO_OBRA,
(ING.NOM1||' '||ING.NOM2||' '||ING.APE1||' '||ING.APE2) AS ING_CARGO, ING.DOC_IDENT,
Ma.MATERIAL_ID, Ma.MATERIAL,
C.DOC_IDENTIDAD, (C.NOM1||' '||C.NOM2||' '||C.APE1||' '||C.APE2) AS CLIENTE_OBRA
FROM OBRA O
INNER JOIN INGENIERO ING   ON ING.INGENIERO_ID = O.INGENIERO_ID
INNER JOIN OBRA_MAESTRO OM ON OM.NRO_OBRA = O.NRO_OBRA
INNER JOIN MAESTRO M       ON M.MAESTRO_ID = OM.MAESTRO_ID
INNER JOIN DETALLE_OBRA DO ON DO.NRO_OBRA = O.NRO_OBRA
INNER JOIN MATERIAL Ma     ON Ma.MATERIAL_ID = DO.MATERIAL_ID
INNER JOIN CLIENTE C       ON C.CLIENTE_ID = O.CLIENTE_ID
WHERE ING.NOM1 = 'JUAN' 
AND ING.NOM2 = 'PABLO' 
AND ING.APE1 = 'HENAO'
AND ING.APE2 = 'ARANGO';

SELECT m.material_id, m.material, m.unidad_med, m.costo, m.existencia
FROM MATERIAL M
INNER JOIN DETALLE_OBRA DO ON DO.MATERIAL_ID = M.MATERIAL_ID 
INNER JOIN OBRA O          ON O.NRO_OBRA = DO.NRO_OBRA
WHERE O.NRO_OBRA = 1;

SELECT O.NRO_OBRA, (C.NOM1||' '||C.NOM2||' '||C.APE1||' '||C.APE2) AS CLIENTE_OBRA
FROM OBRA O
INNER JOIN CLIENTE C ON C.CLIENTE_ID = O.CLIENTE_ID
WHERE O.VALOR_NETO >= (SELECT MAX(VALOR_NETO) FROM OBRA);

-- Option 1 --

select
    MAX(M.MATERIAL_ID),
		MAX(m.material) AS MATERIAL_MAS_UTILIZADO,
		max(count(D.material_id)) as VECES_UTILIZADO
from
		detalle_obra d
join 
		material m on d.material_id = m.material_id
group by 
		m.material_id, M.material, D.material_ID;

-- Option 2 --

SELECT
    D.MATERIAL_ID,
    M.MATERIAL,
    COUNT(D.MATERIAL_ID) AS NRO_VECES_UTILIZADO
FROM
    DETALLE_OBRA D
JOIN
    MATERIAL M ON D.MATERIAL_ID = M.MATERIAL_ID
GROUP BY
    D.MATERIAL_ID, M.MATERIAL
ORDER BY
    NRO_VECES_UTILIZADO DESC
FETCH FIRST 1 ROW ONLY;

SELECT *
FROM OBRA
WHERE TO_CHAR(FECHA,'YYYY') = '2022';

SELECT COUNT(TIPO_OBRA_ID) AS NRO_OBRAS_POR_TIPO, TIPO_OBRA_ID
FROM OBRA
WHERE TO_CHAR(FECHA, 'MM-YYYY') = '04-2023'
GROUP BY TIPO_OBRA_ID
ORDER BY NRO_OBRAS_POR_TIPO DESC;

SELECT SUM(O.VALOR_NETO) AS TOTAL_POR_TIPO_OBRA, O.TIPO_OBRA_ID
FROM OBRA O
GROUP BY O.TIPO_OBRA_ID;

SELECT C.NRO_FACTURA, C.FECHA, P.NOMBRE, CM.MATERIAL_ID, M.MATERIAL, CM.CANTIDAD
FROM COMPRA C
JOIN PROVEEDOR P ON P.PROVEEDOR_ID = C.PROVEEDOR_ID
JOIN COMPRA_MATERIAL CM ON CM.NRO_FACTURA = C.NRO_FACTURA
JOIN MATERIAL M ON M.MATERIAL_ID = CM.MATERIAL_ID
WHERE C.TOTAL_PAGAR BETWEEN 10000 AND 1000000;

SELECT O.VALOR_NETO AS OBRA_MENOS_COSTOSA, (C.NOM1||' '||C.NOM2||' '||C.APE1||' '||C.APE2) AS CLIENTE_OBRA
FROM OBRA O
JOIN CLIENTE C ON C.CLIENTE_ID = O.CLIENTE_ID
WHERE O.VALOR_NETO <= (SELECT MIN(VALOR_NETO) FROM OBRA)

SELECT COUNT(*) AS NRO_OBRAS_FORMA_PAGO_1_AÑO
FROM OBRA
WHERE FORMA_PAGO = '1 AÑO';

SELECT COUNT(C.TOTAL_PAGAR) AS VALOR_TOTAL_COMPRAS_A_PROVEEDOR, P.NOMBRE
FROM PROVEEDOR P
JOIN COMPRA C ON C.PROVEEDOR_ID = P.PROVEEDOR_ID
WHERE P.NOMBRE = 'ARGOS' AND C.PROVEEDOR_ID = P.PROVEEDOR_ID
GROUP BY P.NOMBRE;

SELECT 
    COUNT(C.PROVEEDOR_ID) AS NRO_COMPRAS_POR_PROV,
    AVG(C.TOTAL_PAGAR) AS PROM_COMPRAS_A_PROV,
    SUM(C.TOTAL_PAGAR) AS NETO_COMPRAS_A_PROV,
    C.PROVEEDOR_ID
FROM 
    PROVEEDOR P
JOIN 
    COMPRA C ON C.PROVEEDOR_ID = P.PROVEEDOR_ID
GROUP BY 
    C.PROVEEDOR_ID;

SELECT
	AVG(C.TOTAL_PAGAR) AS PROM_NETO_COMPRAS_A_PROV,
	P.NOMBRE
FROM
	PROVEEDOR P
JOIN COMPRA C ON C.PROVEEDOR_ID = P.PROVEEDOR_ID
GROUP BY P.NOMBRE;

SELECT 
	COUNT(O.TIPO_OBRA_ID) AS VECES_REALIZADA, T_O.TIPO_OBRA, O.TIPO_OBRA_ID
FROM
	OBRA O
JOIN 
	TIPO_OBRA T_O ON T_O.TIPO_OBRA_ID = O.TIPO_OBRA_ID
GROUP BY 
	O.TIPO_OBRA_ID, T_O.TIPO_OBRA
ORDER BY
	VECES_REALIZADA DESC
FETCH FIRST 1 ROW ONLY;

SELECT 
    COUNT(O.INGENIERO_ID) AS ING_A_CARGO_MAS_OBRAS, 
    (ING.NOM1||' '||ING.NOM2||' '||ING.APE1||' '||ING.APE2) AS ING_CARGO
FROM 
    OBRA O
JOIN 
    INGENIERO ING ON ING.INGENIERO_ID = O.INGENIERO_ID
GROUP BY 
    O.INGENIERO_ID, ING.NOM1, ING.NOM2, ING.APE1, ING.APE2
ORDER BY 
    ING_A_CARGO_MAS_OBRAS DESC
FETCH FIRST 1 ROW ONLY;

CREATE OR REPLACE VIEW MATERIALES_SIN_EXISTENCIAS AS
SELECT *
FROM MATERIAL
WHERE EXISTENCIA = 0;

CREATE OR REPLACE VIEW OBRA_MAS_COSTOSA AS
SELECT *
FROM OBRA O
WHERE O.VALOR_NETO >= (SELECT MAX(VALOR_NETO) FROM OBRA);
