-- CREATE SEQUENCE --

CREATE SEQUENCE NEXT_PK_MATERIAL_ID
    INCREMENT BY 1
    START WITH 10
    MINVALUE 10
    MAXVALUE 18
    CYCLE
    CACHE 8;

CREATE SEQUENCE NEXT_PK_PROVEEDOR_ID
    INCREMENT BY 1
    START WITH 90
    MINVALUE 90
    MAXVALUE 94
    CYCLE
    CACHE 4;

CREATE SEQUENCE NEXT_PK_MAESTRO_ID
    INCREMENT BY 1
    START WITH 30
    MINVALUE 30
    MAXVALUE 34
    CYCLE
    CACHE 4;

CREATE SEQUENCE NEXT_PK_INGENIERO_ID
    INCREMENT BY 1
    START WITH 20
    MINVALUE 20
    MAXVALUE 28
    CYCLE
    CACHE 8;

CREATE SEQUENCE NEXT_PK_TIPO_OBRA_ID
    INCREMENT BY 1
    START WITH 70
    MINVALUE 70
    MAXVALUE 75
    CYCLE
    CACHE 5;

CREATE SEQUENCE NEXT_PK_CLIENTE_ID
    INCREMENT BY 1
    START WITH 50
    MINVALUE 50
    MAXVALUE 55
    CYCLE
    CACHE 5;

CREATE SEQUENCE NEXT_PK_NRO_FACTURA
    INCREMENT BY 1
    START WITH 500
    MINVALUE 500
    MAXVALUE 503
    CYCLE
    CACHE 3;

CREATE SEQUENCE NEXT_PK_COMPRA_MATERIAL_ID
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9
    CYCLE
    CACHE 8;

CREATE SEQUENCE NEXT_PK_OBRA
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 12
    CYCLE
    CACHE 11;
    
CREATE SEQUENCE NEXT_PK_OBRA_MAESTRO_ID
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 8
    CYCLE
    CACHE 7;

CREATE SEQUENCE NEXT_PK_DETALLE_OBRA
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10
    CYCLE
    CACHE 9;

-- DROP SEQUENCE --

DROP SEQUENCE NEXT_PK_MATERIAL_ID;
DROP SEQUENCE NEXT_PK_PROVEEDOR_ID;
DROP SEQUENCE NEXT_PK_MAESTRO_ID;
DROP SEQUENCE NEXT_PK_INGENIERO_ID;
DROP SEQUENCE NEXT_PK_TIPO_OBRA_ID;
DROP SEQUENCE NEXT_PK_CLIENTE_ID;
DROP SEQUENCE NEXT_PK_NRO_FACTURA;
DROP SEQUENCE NEXT_PK_COMPRA_MATERIAL_ID;
DROP SEQUENCE NEXT_PK_OBRA;
DROP SEQUENCE NEXT_PK_OBRA_MAESTRO_ID;
DROP SEQUENCE NEXT_PK_DETALLE_OBRA;