UPDATE DETALLE_OBRA
SET costo = (
    SELECT NVL(material.costo,0)*(1+0.1038)
    FROM MATERIAL 
    WHERE material.material_id = detalle_obra.material_id
);

UPDATE DETALLE_OBRA
SET total = (
    NVL(detalle_obra.costo,0)*detalle_obra.cantidad
);

ALTER TABLE OBRA
ADD CONSTRAINT ck_forma_pago 
CHECK (forma_pago IN ('1 AÑO', '6 MESES', 'CONTADO'));

UPDATE OBRA
SET PLAZO = 
    CASE 
        WHEN FORMA_PAGO = '1 AÑO' THEN 12
        WHEN FORMA_PAGO = '6 MESES' THEN 6
        WHEN FORMA_PAGO = 'CONTADO' THEN 0
        ELSE NULL -- or some default value
    END;

UPDATE OBRA
SET VALOR_TOTAL = (
    SELECT SUM(DETALLE_OBRA.TOTAL)
    FROM DETALLE_OBRA
    WHERE DETALLE_OBRA.NRO_OBRA = OBRA.NRO_OBRA
);

ALTER TABLE OBRA
ADD PORC_DCTO NUMBER(3, 2) NULL
    CONSTRAINT CK_PORC_DCTO CHECK (PORC_DCTO >= 0 AND PORC_DCTO <= 1);

UPDATE OBRA
SET PORC_DCTO = 
    CASE
        WHEN FORMA_PAGO = 'CONTADO' THEN 0.20
        ELSE 0
    END;

ALTER TABLE OBRA
ADD SUB_TOTAL NUMBER(16, 2) NULL;

UPDATE OBRA
SET SUB_TOTAL = OBRA.VALOR_TOTAL * (1 - OBRA.PORC_DCTO);

ALTER TABLE OBRA
ADD PORC_IVA NUMBER(3, 2) NULL
CONSTRAINT CK_PORC_IVA CHECK (PORC_IVA >= 0 AND PORC_IVA <= 1);

UPDATE OBRA
SET PORC_IVA = 0.19

ALTER TABLE OBRA
ADD VALOR_NETO NUMBER(38,2) NULL;

UPDATE OBRA
SET VALOR_NETO = OBRA.SUB_TOTAL * (1 + OBRA.PORC_IVA);

UPDATE OBRA
SET PAGO_INICIAL = OBRA.VALOR_NETO * 0.20;

UPDATE OBRA
SET SALDO = OBRA.VALOR_NETO - OBRA.PAGO_INICIAL;

UPDATE COMPRA_MATERIAL
SET TOTAL = CANTIDAD * COSTO_UNID;

UPDATE COMPRA
SET TOTAL_PAGAR = (
	SELECT SUM(COMPRA_MATERIAL.TOTAL)
	FROM COMPRA_MATERIAL
	WHERE COMPRA_MATERIAL.NRO_FACTURA = COMPRA.NRO_FACTURA
);